Document: cert
Title: Debian cert Manual
Author: <insert document author here>
Abstract: This manual describes what cert is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cert/cert.sgml.gz

Format: postscript
Files: /usr/share/doc/cert/cert.ps.gz

Format: text
Files: /usr/share/doc/cert/cert.text.gz

Format: HTML
Index: /usr/share/doc/cert/html/index.html
Files: /usr/share/doc/cert/html/*.html
